import {
  Controller,
  Delete,
  Get,
  HTTPResult,
  JSONBody,
  Parameter,
  Post,
  Put,
} from "@antelopejs/interface-api";
import { GetModel } from "@antelopejs/interface-database-decorators";
import { AuthUserWithPermission } from "@antelopejs/interface-dms/guards";
import { AuthOwnerOnly, AuthRawUser } from "@antelopejs/interface-dms/auth";
import type { User } from "@antelopejs/interface-dms/auth/db";
import { z } from "zod";
import {
  AutomationTemplateModel,
  type AutomationTemplateRow,
  type TemplateUsage,
} from "../db/models/automation_template.model";
import { ProcedureModel } from "../db/models/procedure.model";
import { BuilderPageController } from "../pages/builder";
import type { TemplateCache } from "../runtime/resolveSubgraph";
import { subscriptions } from "../runtime/subscriptions";
import { findTemplateRefCycle } from "../runtime/validateTemplate";
import { DATABASE_NAME, FETCH_ALL_LIMIT } from "../types/constants";
import {
  type GraphNode,
  type GroupPort,
  type ProcedureGraph,
  walkNodesRecursive,
} from "../types/graph";
import type { Paginated } from "../types/pagination";
import {
  groupPortSchema,
  parseAndValidate,
  procedureGraphSchema,
} from "./graphSchema";

const templateBodySchema = z.object({
  name: z.string().min(1),
  description: z.string().optional(),
  icon: z.string().optional(),
  ports: z.array(groupPortSchema),
  subgraph: procedureGraphSchema,
});

interface ParsedTemplateBody {
  name: string;
  description?: string;
  icon?: string;
  ports: GroupPort[];
  subgraph: ProcedureGraph;
}

function parseTemplateBody(body: unknown): ParsedTemplateBody {
  return parseAndValidate(templateBodySchema, body, (d) => d.subgraph);
}

// Pre-load every template once per request and build the synchronous lookup
// `findTemplateRefCycle` needs. We optionally splice in a candidate (the
// in-flight POST/PUT) so the DFS can resolve self-references through it.
async function buildTemplateRefLookup(candidate?: {
  id: string;
  subgraph: ProcedureGraph;
}): Promise<TemplateCache> {
  const templateModel = GetModel(AutomationTemplateModel, DATABASE_NAME);
  const all = await templateModel.list({ page: 0, limit: FETCH_ALL_LIMIT });
  const byId = new Map<string, { subgraph: ProcedureGraph }>();
  for (const t of all.results) {
    byId.set(t._id, { subgraph: t.subgraph });
  }
  if (candidate) {
    byId.set(candidate.id, { subgraph: candidate.subgraph });
  }
  return {
    get(id: string) {
      return byId.get(id);
    },
  };
}

// Count usages per templateId via a single procedures scan (avoids N round-trips
// through `findUsages`). Reuses the shared `walkNodesRecursive` (also used by
// `AutomationTemplateModel.findUsages`) so nested group instances are tallied.
async function computeUsageCounts(): Promise<Map<string, number>> {
  const procedureModel = GetModel(ProcedureModel, DATABASE_NAME);
  const procs = await procedureModel.list({ page: 0, limit: FETCH_ALL_LIMIT });
  const counts = new Map<string, number>();
  for (const p of procs.results) {
    let graph: ProcedureGraph;
    try {
      graph = JSON.parse(p.graph) as ProcedureGraph;
    } catch {
      continue;
    }
    for (const node of walkNodesRecursive(graph)) {
      if (node.kind !== "group") continue;
      const templateId = (node as GraphNode & { templateId?: string })
        .templateId;
      if (!templateId) continue;
      counts.set(templateId, (counts.get(templateId) ?? 0) + 1);
    }
  }
  return counts;
}

interface TemplateWithUsage extends AutomationTemplateRow {
  usageCount: number;
}

/** Result of DELETE /templates/:id — the removed id and how many usages forked. */
interface RemoveTemplateResult {
  _id: string;
  forked: number;
}

// A unique sentinel id used for the cycle check on POST. The new template's
// real id is generated by the DB on insert, so we feed the cycle detector a
// placeholder. No other template can reference this id (it never escapes this
// request), which means a self-cycle via the candidate is only possible if the
// candidate's own subgraph references it — which would require the client to
// have already sent the placeholder, which won't happen organically.
const POST_CANDIDATE_ID = "__candidate__";

@AuthOwnerOnly()
export class TemplatesController extends Controller(
  "/api/automation/templates",
) {
  @Get("")
  async list(
    @AuthRawUser() _user: User,
    @Parameter("page", "query") page?: string,
    @Parameter("limit", "query") limit?: string,
  ): Promise<Paginated<TemplateWithUsage>> {
    const templateModel = GetModel(AutomationTemplateModel, DATABASE_NAME);
    const pageNum = page ? Number(page) : 0;
    const limitNum = limit ? Number(limit) : 20;
    const [listed, usageCounts] = await Promise.all([
      templateModel.list({ page: pageNum, limit: limitNum }),
      computeUsageCounts(),
    ]);
    return {
      ...listed,
      results: listed.results.map((t) => ({
        ...t,
        usageCount: usageCounts.get(t._id) ?? 0,
      })),
    };
  }

  @Get("/:id")
  async getOne(
    @AuthRawUser() _user: User,
    @Parameter("id", "param") id: string,
  ): Promise<AutomationTemplateRow> {
    const templateModel = GetModel(AutomationTemplateModel, DATABASE_NAME);
    const template = await templateModel.getById(id);
    if (!template) {
      throw new HTTPResult(404, { error: `template "${id}" not found` });
    }
    return template;
  }

  @Post("")
  async create(
    @AuthUserWithPermission(BuilderPageController) _user: User,
    @JSONBody() body: unknown,
  ): Promise<AutomationTemplateRow> {
    const data = parseTemplateBody(body);
    const lookup = await buildTemplateRefLookup({
      id: POST_CANDIDATE_ID,
      subgraph: data.subgraph,
    });
    const cycle = findTemplateRefCycle(
      POST_CANDIDATE_ID,
      data.subgraph,
      lookup,
    );
    if (cycle) {
      throw new HTTPResult(400, {
        error: "template reference cycle",
        cycle,
      });
    }
    const templateModel = GetModel(AutomationTemplateModel, DATABASE_NAME);
    const created = await templateModel.create({
      name: data.name,
      description: data.description ?? "",
      icon: data.icon ?? "",
      ports: data.ports,
      subgraph: data.subgraph,
    });
    await subscriptions.onTemplateChange(created._id);
    return created;
  }

  @Put("/:id")
  async update(
    @AuthUserWithPermission(BuilderPageController) _user: User,
    @Parameter("id", "param") id: string,
    @JSONBody() body: unknown,
  ): Promise<AutomationTemplateRow> {
    const data = parseTemplateBody(body);
    const templateModel = GetModel(AutomationTemplateModel, DATABASE_NAME);
    const existing = await templateModel.getById(id);
    if (!existing) {
      throw new HTTPResult(404, { error: `template "${id}" not found` });
    }
    const lookup = await buildTemplateRefLookup({
      id,
      subgraph: data.subgraph,
    });
    const cycle = findTemplateRefCycle(id, data.subgraph, lookup);
    if (cycle) {
      throw new HTTPResult(400, {
        error: "template reference cycle",
        cycle,
      });
    }
    const updated = await templateModel.updateById(id, {
      name: data.name,
      description: data.description ?? "",
      icon: data.icon ?? "",
      ports: data.ports,
      subgraph: data.subgraph,
    });
    await subscriptions.onTemplateChange(id);
    return updated;
  }

  @Delete("/:id")
  async remove(
    @AuthUserWithPermission(BuilderPageController) _user: User,
    @Parameter("id", "param") id: string,
    @Parameter("force", "query") force?: string,
  ): Promise<RemoveTemplateResult> {
    const templateModel = GetModel(AutomationTemplateModel, DATABASE_NAME);
    const existing = await templateModel.getById(id);
    if (!existing) {
      throw new HTTPResult(404, { error: `template "${id}" not found` });
    }
    const usages = await templateModel.findUsages(id);
    const forced = force === "1" || force === "true";
    if (usages.length > 0 && !forced) {
      throw new HTTPResult(409, {
        error: "template has usages; pass ?force=1 to fork them",
        usages,
      });
    }
    if (forced) {
      // Fork BEFORE deleting from the cache — forkUsageToLocal reads
      // templateCache to deep-clone the subgraph. onTemplateDelete() below
      // removes the cache entry; doing it the other way around leaves
      // dangling references.
      for (const usage of usages) {
        await subscriptions.forkUsageToLocal(usage.procedureId, usage.nodeId);
      }
    }
    await templateModel.deleteById(id);
    await subscriptions.onTemplateDelete(id);
    if (forced && usages.length > 0) {
      // Forking rewrote those procedures' graphs in the DB. onTemplateDelete's
      // revalidate finds no usages now (they're forked), so it won't reconcile
      // them — propagate a procedure change so this instance AND peers refresh
      // their live graph for the forked procedures.
      await subscriptions.onProcedureChange();
    }
    return { _id: id, forked: forced ? usages.length : 0 };
  }

  @Get("/:id/usages")
  async usages(
    @AuthRawUser() _user: User,
    @Parameter("id", "param") id: string,
  ): Promise<TemplateUsage[]> {
    const templateModel = GetModel(AutomationTemplateModel, DATABASE_NAME);
    return await templateModel.findUsages(id);
  }
}
